---
name: Request for Discussion
description: Propose a topic for discussion (see [RFD_GUIDE.md](https://github.com/openchami/.github/blob/main/RFD_GUIDE.md) for philosophy and examples)
title: "[RFD]: "
labels: rfd
assignees: []
body:
  - type: input
    id: goal
    attributes:
      label: Decision Goal
      description: What decision or outcome do we want from this discussion?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What area does this RFD touch?
      options:
        - Architecture
        - Code Quality
        - Feature
        - Process
        - Tooling
        - Other
    validations:
      required: true

  - type: input
    id: stakeholders
    attributes:
      label: Stakeholders / Affected Areas
      description: Who is impacted (teams, users, systems)?
  
  - type: input
    id: deadline
    attributes:
      label: Decision Needed By
      description: Optional — milestone, summit, or release this ties to.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the current state and why change is needed.
      placeholder: >
        Example: We currently have three teapots in the office, which waste
        electricity and counter space, making tea preparation inefficient.

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Outline your recommended solution.
      placeholder: >
        Example: Install a hot-tap in the sink for ~$11. This provides
        unlimited 100C water and frees counter space.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other options did you consider and why did you reject them?
      placeholder: |
        - Campfire — not practical due to fire code
        - Samovar — more expensive and energy-intensive
        - Hire tea-maker — budget and space constraints

  - type: textarea
    id: considerations
    attributes:
      label: Other Considerations
      description: Risks, downsides, or open questions.
      placeholder: >
        Example: Hot taps may be unsafe around small children. Ensure labeling
        and placement minimize risk.

  - type: textarea
    id: links
    attributes:
      label: Related Docs / PRs
      description: Provide links to supporting material (design docs, PRs, specs).

  - type: markdown
    attributes:
      value: |
        ## Outcome (to be filled in after discussion)

        - [ ] Accepted
        - [ ] Rejected
        - [ ] Needs RFC
        - [ ] Deferred
        - [ ] Other: ________

        **Decision date:**  
        **Recorded by:**

---