# This workflow checks if the commits in a pull request have a Signed-off-by line.
# If any commit is missing this line, it will fail the workflow and report the SHA(s) of the commits that need to be signed off.
# It is designed to run on pull requests targeting the OpenCHAMI repository, ensuring that all contributions comply with the Developer Certificate of Origin (D
#CO) requirements.
# The workflow uses the `actions/checkout` action to check out the code and then verifies
# the commit messages for the Signed-off-by line. If any commits are found without this line,
# it will output an error message with the commit SHA(s) that need to be addressed.
# This workflow is intended to be used in a sandbox environment for testing purposes.
# It is not intended for production use and should be modified as necessary for your specific requirements.
name: DCO Check (sandbox)

on: [pull_request]

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Verify Signed-off-by line(s)
        shell: bash
        run: |
          missing=""
          while read -r sha; do
            if ! git log -1 --format=%B "$sha" | grep -q '^Signed-off-by:'; then
              missing="$missing $sha"
            fi
          done < <(git log --pretty=format:%H ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          if [ -n "$missing" ]; then
            echo "::error title=DCO validation failed::Commit(s) missing Signed-off-by:$missing"
            exit 1
          fi
