# This is a starter template that calls the org reusable workflow.
# It appears in Actions → "New workflow" for any repo in the org.

name: Go: Build & Release (GoReleaser)

on:
  # Release on version tags; tweak to your liking
  push:
    tags:
      - "v*"
  # Allow manual runs
  workflow_dispatch:
    inputs:
      release_notes:
        description: "Optional release notes (appended)"
        required: false
        default: ""

permissions:
  contents: write          # needed to create releases
  packages: write          # if you publish images or packages (optional)

jobs:
  release:
    uses: OpenCHAMI/github-actions/.github/workflows/go-build-release.yml@main
    # If your reusable workflow defines inputs under `on: workflow_call: inputs:`,
    # pass them through here. The examples below are common knobs—delete or edit as needed.
    with:
      go-version: "1.22.x"                # example input
      goreleaser-config: ".goreleaser.yaml"  # example input
      extra-notes: "${{ github.event.inputs.release_notes }}" # example input
    # Inherit caller repo secrets (e.g., GITHUB_TOKEN, HOMEBREW_TOKEN, GHCR creds)
    secrets: inherit
